name: prod-deploy

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Package
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:prod

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build folder to S3
        run: aws s3 sync build/ s3://slogup-dale-prod-deploy --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E121MH32UPE3LP --paths "/*"
